### ISSUE TITLE
RPC call TimeOut and webSocket not connectd

### ISSUE THREAD

**Issue by tosker12345** [mongoose-os-libs/wifi-setup-web-ui#4]
Hello, I am trying to add a Wi-Fi settings web UI to the firmware. But unfortunately it doesn't work.
First. Add mos.yml lib to mongoose-os-libs/wifi-setup-web-ui and flash it on my device.
The webpage access is fine, but the'websocket connected' phrase in the result is only 'no'. Nevertheless, I entered ssid and pass and clicked the save button. However the result is Timeout.
![no](https://user-images.githubusercontent.com/34476405/96225767-8a1f8a80-0fcc-11eb-92a3-71a6a8a3f190.png)

![화면 캡처 2020-10-16 161634](https://user-images.githubusercontent.com/34476405/96225781-91df2f00-0fcc-11eb-9219-f455639927f9.png)

And I cloned  mongoose-apps/wifi-setup-web and build and flashed the firmware. However, the result is the same as before.
I using esp32.
here My mos.yml in lib part codes
```
libs
 - origin: https://github.com/mongoose-os-libs/rpc-loopback
  - origin: https://github.com/mongoose-os-libs/rpc-service-config
  - origin: https://github.com/mongoose-os-libs/rpc-service-fs
  - origin: https://github.com/mongoose-os-libs/rpc-service-ota
  - origin: https://github.com/mongoose-os-libs/rpc-uart
  - origin: https://github.com/mongoose-os-libs/rpc-common
  - origin: https://github.com/mongoose-os-libs/http-server
  - origin: https://github.com/mongoose-os-libs/wifi
  - origin: https://github.com/mongoose-os-libs/mjs
  - origin: https://github.com/mongoose-os-libs/adc
  - origin: https://github.com/mongoose-os-libs/mqtt
  - origin: https://github.com/mongoose-os-libs/aws
  - origin: https://github.com/mongoose-os-libs/sntp
  - origin: https://github.com/mongoose-os-libs/ota-shadow
  - origin: https://github.com/mongoose-os-libs/ca-bundle
  - origin: https://github.com/mongoose-os-libs/wifi-setup-web-ui
```
I wait for answer. Thank you.

**Comment by tosker12345** [comment]
I found another error. I'm add for debuging alert to json-rpc-ws.js at reconnect function.  So I'm geted result at firmware is repeat 1 second trying WS connection.  Could help solve my problem?

![image (1)](https://user-images.githubusercontent.com/34476405/96235293-92c88e80-0fd5-11eb-9571-8233b5dae7bc.png)

**Comment by tosker12345** [comment]
I found my problem. this lib need **### "https://github.com/mongoose-os-libs/rpc-ws"**

**Comment by rojer** [comment]
i added rpc-ws as a dependency for this library, thank you!
